### ISSUE TITLE
How to build this source

### ISSUE THREAD

**Issue by tdeb-ari** [R1BN/GPMAV#1]
How can I build this source code at Visual Studio 2012?

**Comment by tanmoydeb07** [comment]
Could you please help me to build this project??

**Comment by tdeb-ari** [comment]
Any update please? or this development is stopped permanently...i would like to contribute further

**Comment by gr01d** [comment]
I will upload the source codes that can be built using VS2012, when I have the time.

**Comment by gr01d** [comment]
Uploading the codes now. I've tested this on Visual Studio 2012

**Comment by tdeb-incise** [comment]
Soubds cool
