### ISSUE TITLE
Error after installation

### ISSUE THREAD

**Issue by mrkaban** [R1BN/GPMAV#2]
Welcome installed anti-virus, but the following error occurs after you install, and it does not run respectively.
"An Error has occurred!"
![default](https://cloud.githubusercontent.com/assets/14289360/22982464/ceb9b302-f3d1-11e6-9a7c-011e315c69ee.jpg)

**Comment by gr01d** [comment]
can you translate the screenshot to english? what Operating System platform [x64 or x86] do you use and what version of the antivirus? this project is not under development since I do not use Microsoft Windows Operating System however I am recoding this to make it crossplatform if I can do it.

**Comment by mrkaban** [comment]
Hello! The Windows platform! I have three computers at home, two of them windows 7 x64 and one Windows 10 x64. Problems were at all.

Translation error: "initializer type '*' threw an exception."
![default](https://cloud.githubusercontent.com/assets/14289360/25576760/89a5782e-2e8b-11e7-8167-1a79f4bdc358.JPG)

**Comment by gr01d** [comment]
I'm sorry for the late replies, Currently the GPM AV does not support the Windows x64 architecture. I cannot help at this time, my main Computer needs a new component to run...

**Comment by mrkaban** [comment]
Understood, I will definitely test on a 32-bit architecture. Thanks for the support of open source antivirus! Is there a plan for solving the problem in the future with the x64 architecture?

**Comment by gr01d** [comment]
Yes, I am planning to support the x64 architecture since almost all new PC/Laptop now comes with the preinstalled x64 of Windows and x64 architecture. However, I currently don't have funds to buy a new component for my main PC in which my GPMAV development files and setups is  located.

**Comment by mrkaban** [comment]
Got it. I think you should use such kraudfanding site Kickstarter. And there to collect the necessary amount. I think that people will be happy to help. To make a reward, the first thanks in words, the second thanks on the site, the second thanks in the program, the third all of the above plus special technical support.

Ticket will be closed, because the question is removed.

**Comment by gr01d** [comment]
Hi please translate the error message to english. Thank You
