### ISSUE TITLE
I found some problems

### ISSUE THREAD

**Issue by mrkaban** [R1BN/GPMAV#3]
Hello, I found some problems. The first problem is that it finds, but can not delete files from folders whose name is written in Russian. The second problem is that the real-time check probably does not work. When trying to turn on protection in real time, it gives an error. I decided to check, suddenly it still works, launched the old virus - Virus.Win32.Sality.s(Kaspersky) , it is in the base ClamAV, and when the scanner detects it, but the protection in real time does not.
![default](https://cloud.githubusercontent.com/assets/14289360/26712941/f70f7f9c-4793-11e7-993e-1572d2b87906.jpg)
![2](https://cloud.githubusercontent.com/assets/14289360/26712940/f70e8fb0-4793-11e7-943e-c7e07f06f1f0.jpg)

**Comment by gr01d** [comment]
Please translate the error message to english. Thank You

**Comment by mrkaban** [comment]
"The specified service already exists"

**Comment by gr01d** [comment]
it means that the realtime service is enabled and the service is installed. can you check process manager if the "GPMClamAVRTSvc.exe" is running. Real-time protection is still under beta stage.
